name: Check Terraform Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Check Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: hashicorp/setup-terraform@v2

      - name: Init
        run: terraform init

      - name: Format
        run: terraform fmt -recursive -check

      - name: Validate
        run: terraform validate -no-color
