name: Publish Github Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    tags:
      - "*"
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
